import { requireSuperAdmin } from '../../lib/auth';

const html = String.raw`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>系统后台 · 家谱</title><style>
:root{font-family:"Microsoft YaHei",system-ui,sans-serif;color:#35241e;background:#f5eee1;font-size:16px}*{box-sizing:border-box}body{margin:0}.top{background:#852824;color:#fff8e8;padding:18px 28px;display:flex;align-items:center;justify-content:space-between}.top h1{margin:0;font:700 25px serif}.top a{color:#fff;text-decoration:none;border:1px solid #e2be7e;padding:8px 14px;border-radius:9px}.shell{display:grid;grid-template-columns:220px 1fr;min-height:calc(100vh - 70px)}nav{padding:22px 14px;background:#fffaf1;border-right:1px solid #dfc594}nav button{display:block;width:100%;border:0;background:transparent;padding:13px 15px;border-radius:9px;text-align:left;font:700 15px inherit;color:#603c30;cursor:pointer;margin-bottom:5px}nav button.active{background:#922d28;color:#fff}main{padding:26px;overflow:auto}h2{margin-top:0;color:#792721}.cards{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:14px}.card,.panel{background:#fffdf8;border:1px solid #dfc594;border-radius:13px;padding:18px;box-shadow:0 8px 26px #6b40200d}.card strong{display:block;font-size:30px;color:#922d28;margin-top:8px}.toolbar{display:flex;gap:10px;margin-bottom:14px}.toolbar input{min-width:280px;padding:10px 12px;border:1px solid #cda66f;border-radius:8px}table{width:100%;border-collapse:collapse;background:#fffdf8;font-size:14px}th,td{text-align:left;padding:11px;border-bottom:1px solid #ead9b9;vertical-align:top}th{color:#7b2a25;background:#fff7e8;position:sticky;top:0}tr[data-id]{cursor:pointer}tr[data-id]:hover{background:#fff6e5}.badge{display:inline-block;padding:3px 8px;border-radius:99px;background:#eee2ca}.badge.red{background:#fde3df;color:#98271f}.actions{display:flex;gap:8px;flex-wrap:wrap}.actions button,.backup-button{border:1px solid #b98242;background:#fff8ea;color:#792721;border-radius:7px;padding:9px 14px;cursor:pointer;font:700 15px inherit}.actions .danger,.backup-button{background:#922d28;color:white}.backup-button:disabled{opacity:.55;cursor:wait}.warning{padding:14px;border:2px solid #b9342d;background:#fff0ed;color:#7f1f1a;border-radius:10px;font-weight:700}.muted{color:#826f64}.hidden{display:none!important}.error{padding:12px;border-left:4px solid #a92d28;background:#fff0ed;color:#8b211d;margin-bottom:14px}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.back{border:0;background:none;color:#922d28;font-weight:700;cursor:pointer;margin-bottom:12px}@media(max-width:850px){.shell{grid-template-columns:1fr}nav{display:flex;overflow:auto;border-right:0;border-bottom:1px solid #dfc594;padding:10px}nav button{white-space:nowrap;margin:0}.cards{grid-template-columns:1fr 1fr}main{padding:16px}.detail-grid{grid-template-columns:1fr}.table-wrap{overflow:auto}}
</style></head><body><header class="top"><h1>家谱 · 系统后台</h1><a href="/">返回家谱平台</a></header><div class="shell"><nav id="nav"><button data-view="overview" class="active">后台首页</button><button data-view="users">用户管理</button><button data-view="families">族谱概览</button><button data-view="logs">系统日志</button><button data-view="backup">生产备份</button></nav><main><div id="error"></div><section id="content"><p>正在读取系统数据…</p></section></main></div>
<script>
const content=document.querySelector('#content'),errorBox=document.querySelector('#error');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Date(v).toLocaleString('zh-CN'):'—';
async function api(url,init){const r=await fetch(url,init);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'请求失败');return d}
function fail(e){errorBox.innerHTML='<div class="error">'+esc(e.message)+'</div>'}
function activate(view){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));errorBox.innerHTML=''}
async function showOverview(){activate('overview');try{const d=await api('/api/admin?view=overview');content.innerHTML='<h2>后台首页</h2><div class="cards"><div class="card">注册用户<strong>'+d.users+'</strong></div><div class="card">族谱总数<strong>'+d.families+'</strong></div><div class="card">已禁用账号<strong>'+d.disabledUsers+'</strong></div><div class="card">系统日志<strong>'+d.logs+'</strong></div></div>'}catch(e){fail(e)}}
async function showUsers(){activate('users');content.innerHTML='<h2>用户管理</h2><p>正在读取…</p>';try{const d=await api('/api/admin?view=users');content.innerHTML='<h2>用户管理</h2><div class="toolbar"><input id="user-search" placeholder="搜索用户名、昵称、邮箱或手机号"></div><div class="panel table-wrap"><table><thead><tr><th>账号</th><th>联系方式</th><th>注册/最近登录</th><th>状态</th><th>族谱</th><th>人物绑定</th></tr></thead><tbody id="users-body">'+d.users.map(u=>'<tr data-id="'+esc(u.id)+'" data-search="'+esc([u.username,u.nickname,u.email,u.phone].join(' ').toLowerCase())+'"><td><b>'+esc(u.username||'—')+'</b><br><span class="muted">'+esc(u.id)+'</span></td><td>'+esc(u.email||'—')+'<br>'+esc(u.phone||'—')+'</td><td>'+date(u.created_at)+'<br><span class="muted">'+date(u.last_login_at)+'</span></td><td><span class="badge '+(u.status==='ACTIVE'?'':'red')+'">'+esc(u.status)+'</span><br>'+esc(u.system_role)+'</td><td>'+u.family_count+'</td><td>'+(u.person_bound?'已绑定':'未绑定')+'</td></tr>').join('')+'</tbody></table></div>';document.querySelector('#users-body').onclick=e=>{const tr=e.target.closest('tr[data-id]');if(tr)showUser(tr.dataset.id)};document.querySelector('#user-search').oninput=e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll('#users-body tr').forEach(tr=>tr.classList.toggle('hidden',!tr.dataset.search.includes(q)))}}catch(e){fail(e)}}
async function showUser(id){try{const d=await api('/api/admin?view=user&id='+encodeURIComponent(id)),u=d.user;content.innerHTML='<button class="back" id="back-users">← 返回用户列表</button><h2>'+esc(u.username||u.id)+'</h2><div class="detail-grid"><section class="panel"><h3>基本账号信息</h3><p>用户 ID：'+esc(u.id)+'</p><p>昵称：'+esc(u.nickname||'—')+'</p><p>邮箱：'+esc(u.email||'—')+'</p><p>手机号：'+esc(u.phone||'—')+'</p><p>系统角色：'+esc(u.system_role)+'</p><p>状态：'+esc(u.status)+'</p><p>注册：'+date(u.created_at)+'</p><p>最近登录：'+date(u.last_login_at)+'</p><div class="actions"><button class="danger" data-action="DISABLE_USER">禁用账号</button><button data-action="RESTORE_USER">恢复账号</button><button data-action="FORCE_LOGOUT">强制退出</button></div></section><section class="panel"><h3>加入的族谱</h3>'+(d.families.length?d.families.map(f=>'<p><b>'+esc(f.name)+'</b><br><span class="muted">'+esc(f.id)+' · '+esc(f.role)+'</span></p>').join(''):'<p class="muted">尚未加入族谱</p>')+'</section></div><section class="panel" style="margin-top:14px"><h3>相关系统操作记录</h3>'+(d.logs.length?d.logs.map(l=>'<p><b>'+esc(l.action_type)+'</b> · '+date(l.created_at)+'<br><span class="muted">'+esc(l.old_value||'—')+' → '+esc(l.new_value||'—')+'；'+esc(l.reason||'')+'</span></p>').join(''):'<p class="muted">暂无系统操作记录</p>')+'</section>';document.querySelector('#back-users').onclick=showUsers;document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>changeStatus(id,b.dataset.action))}catch(e){fail(e)}}
async function changeStatus(id,action){const labels={DISABLE_USER:'禁用账号',RESTORE_USER:'恢复账号',FORCE_LOGOUT:'强制用户退出登录'},reason=prompt('请输入操作原因：');if(reason===null)return;if(!confirm('确认'+labels[action]+'？该操作会写入系统日志。'))return;try{await api('/api/admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,targetUserId:id,reason})});await showUser(id)}catch(e){fail(e)}}
async function showFamilies(){activate('families');try{const d=await api('/api/admin?view=families');content.innerHTML='<h2>族谱概览</h2><div class="panel table-wrap"><table><thead><tr><th>族谱</th><th>创建者</th><th>成员</th><th>人物</th><th>创建时间</th><th>状态</th></tr></thead><tbody>'+d.families.map(f=>'<tr><td><b>'+esc(f.name)+'</b><br><span class="muted">'+esc(f.id)+'</span></td><td>'+esc(f.creator||'—')+'</td><td>'+f.member_count+'</td><td>'+f.person_count+'</td><td>'+date(f.created_at)+'</td><td>'+esc(f.status||'—')+'</td></tr>').join('')+'</tbody></table></div>'}catch(e){fail(e)}}
async function showLogs(){activate('logs');try{const d=await api('/api/admin?view=logs');content.innerHTML='<h2>系统日志</h2><div class="panel table-wrap"><table><thead><tr><th>时间</th><th>操作人</th><th>操作</th><th>目标用户</th><th>变化</th><th>原因</th></tr></thead><tbody>'+d.logs.map(l=>'<tr><td>'+date(l.created_at)+'</td><td>'+esc(l.operator_name||l.operator_user_id)+'</td><td>'+esc(l.action_type)+'</td><td>'+esc(l.target_name||l.target_user_id||'—')+'</td><td>'+esc(l.old_value||'—')+' → '+esc(l.new_value||'—')+'</td><td>'+esc(l.reason||'—')+'</td></tr>').join('')+'</tbody></table></div>'}catch(e){fail(e)}}
function showBackup(){activate('backup');content.innerHTML='<h2>生产数据库备份</h2><div class="panel"><p class="warning">备份包含账号、会话、联系方式及完整族谱资料，请妥善保管。</p><p>系统会识别当前数据库版本，并以只读方式完整导出该版本的全部业务表，不会修改任何生产数据。</p><button class="backup-button" id="download-backup">生成并下载完整备份</button><p class="muted" id="backup-status">下载完成后，请使用本地恢复验证工具确认备份有效。</p></div>';document.querySelector('#download-backup').onclick=downloadBackup}
async function downloadBackup(){const button=document.querySelector('#download-backup'),status=document.querySelector('#backup-status');button.disabled=true;button.textContent='正在生成安全备份…';status.textContent='请勿关闭页面。';errorBox.innerHTML='';try{const response=await fetch('/api/admin/backups/export',{method:'POST'});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||'备份生成失败')}const blob=await response.blob(),disposition=response.headers.get('content-disposition')||'',match=disposition.match(/filename="([^"]+)"/),name=match?match[1]:'production-database-backup.zip',url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);status.textContent='备份文件已下载。请立即执行本地恢复验证，并安全保存。'}catch(e){fail(e);status.textContent='没有生成或下载不完整备份。'}finally{button.disabled=false;button.textContent='生成并下载完整备份'}}
const views={overview:showOverview,users:showUsers,families:showFamilies,logs:showLogs,backup:showBackup};document.querySelector('#nav').onclick=e=>{const b=e.target.closest('button[data-view]');if(b)views[b.dataset.view]()};showOverview();
</script></body></html>`;

export async function GET(request:Request){
  try{
    await requireSuperAdmin(request);
    return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','Cache-Control':'no-store'}});
  }catch(error){
    if(error instanceof Response)return error;
    console.error('admin page failed',error);
    return new Response('系统后台暂时不可用',{status:500});
  }
}
