DROP TABLE IF EXISTS relationship;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS family;

CREATE TABLE family (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id BIGINT NOT NULL,
    name VARCHAR(80) NOT NULL,
    gender VARCHAR(30),
    generation INT NOT NULL,
    birth_date DATE,
    death_date DATE,
    biography CLOB,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted TINYINT DEFAULT 0 NOT NULL,
    version INT DEFAULT 1 NOT NULL,
    CONSTRAINT fk_person_family FOREIGN KEY (family_id) REFERENCES family(id)
);

CREATE TABLE relationship (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id BIGINT NOT NULL,
    from_person_id BIGINT NOT NULL,
    to_person_id BIGINT NOT NULL,
    relationship_type VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted TINYINT DEFAULT 0 NOT NULL,
    version INT DEFAULT 1 NOT NULL
);
